/* ============================================================================
   ACELERO COMEX — idiomas.js

   Dicionário de traduções. O português vive no próprio index.html (bom para
   SEO e para quem abre com JavaScript desligado); aqui ficam apenas inglês e
   espanhol, com as mesmas chaves `data-i18n`. Ao voltar para o português, o
   main.js restaura o texto original capturado na carga.

   Os valores carregam a mesma marcação inline do original (<em>, <strong>,
   <span class="mono">, <li>…) — quem traduz precisa preservá-la.
   ========================================================================== */

window.ACELERO_IDIOMAS = {

  en: {
    /* navegação */
    'nav.sobre': '<span class="mono">01</span>About',
    'nav.servicos': '<span class="mono">02</span>Services',
    'nav.processo': '<span class="mono">03</span>Process',
    'nav.cases': '<span class="mono">05</span>Cases',
    'nav.contato': '<span class="mono">09</span>Contact',
    'nav.cta': 'Book a consultation',
    'menu.1': 'About Acelero', 'menu.2': 'Services', 'menu.3': 'Process',
    'menu.4': 'Results', 'menu.5': 'Cases', 'menu.6': 'Why we do it',
    'menu.7': 'Guarantees', 'menu.8': 'Frequently asked questions',
    'menu.9': 'Talk to a specialist',

    /* hero */
    'hero.tag.1': 'End-to-end foreign trade management',
    'hero.h.l1': 'Connecting',
    'hero.h.l2': 'the world through',
    'hero.h.l3': '<em>foreign trade.</em>',
    'hero.sub.1': 'Complete import and export management, run with precision and accountability — <strong>from the purchase order to the cargo on your dock</strong>, with the cost locked before you approve the purchase.',
    'hero.cta1.1': 'Book a consultation',
    'hero.cta2.1': 'What we do',
    'hero.kpi.1': 'shipments managed',
    'hero.kpi.2': 'countries operated',
    'hero.kpi.3': 'cleared on the green channel',
    'hero.kpi.4': 'stay with us past 24 months',
    'hero.role.1': 'Scroll',

    /* seções — numeração */
    'hdnum.1': '01 — About', 'hdnum.2': '02 — Services', 'hdnum.3': '03 — Process',
    'hdnum.4': '04 — Results', 'hdnum.5': '05 — Cases', 'hdnum.6': '06 — Why we do it',
    'hdnum.7': '07 — Guarantees', 'hdnum.8': '08 — Questions', 'hdnum.9': '09 — Contact',

    /* sobre */
    'sobre.h.l1': 'We are not another',
    'sobre.h.l2': 'middleman. We are your',
    'sobre.h.l3': '<em>foreign trade</em>',
    'sobre.h.l4': '<em>department.</em>',
    'sobre.txt.1': '<p> ACELERO COMEX was born of a simple frustration: Brazilian companies lose margin, time and sleep because international operations are treated as a jigsaw of disconnected suppliers — one quotes, another ships, another clears customs, and nobody answers for the outcome. </p> <p> We bring all of it under one team, one process and one accountable owner. You talk to one person; we coordinate the rest of the planet. </p>',
    'tri.lbl.1': 'Mission',
    'tri.h.1': 'Make the world reachable for those who produce and sell in Brazil.',
    'tri.p.1': 'Shorten the distance between your company and any supplier or customer on the planet, with full clarity on cost, lead time and risk.',
    'tri.lbl.2': 'Vision',
    'tri.h.2': 'To be the most predictable foreign trade operation in Latin America.',
    'tri.p.2': 'Not the largest. The most dependable — the one where the board can plan a whole quarter without fearing what is coming from the other side of the ocean.',
    'tri.lbl.3': 'Values',
    'tri.h.3': 'Radical transparency, data before opinion, ownership end to end.',
    'tri.p.3': 'If something goes wrong, you hear it from us — before it turns into a loss. No hidden fees, no “that one is not on us”.',

    /* serviços */
    'serv.h.l1': 'Four fronts.',
    'serv.h.l2': 'One <em>single</em> operation.',
    'lead.1': 'You can hire a single front or hand the whole operation to our team. In practice, whoever starts with one ends up moving everything across — because the gain lies precisely in nobody being able to pass the blame to the next link.',
    'card.n.1': 'S/01',
    'card.h.1': 'Import and Export',
    'card.p.1': 'From supplier vetting to customs clearance — and, in the other direction, from label compliance to the certificate of origin. A <em>landed cost</em> simulation before you approve the purchase, not after the invoice lands.',
    'card.b.1': '<span class="mono">Gain</span> You commit to a purchase knowing the final cost on your own shelf, with the margin calculated rather than guessed.',
    'card.cta.1': 'Simulate my operation',
    'card.n.2': 'S/02',
    'card.h.2': 'International Logistics',
    'card.p.2': 'Ocean, air, road and multimodal, on contracts negotiated at volume. We pick the mode against your sales calendar, not the agent’s convenience — and we track every leg to the destination dock.',
    'card.b.2': '<span class="mono">Gain</span> Competitive freight with guaranteed space in peak season, and an ETA you can safely promise your own customer.',
    'card.cta.2': 'Quote my freight',
    'card.n.3': 'S/03',
    'card.h.3': 'Customs Clearance',
    'card.p.3': 'Our own brokerage team, paperwork checked before arrival, and daily contact with the terminals. When a shipment is flagged for inspection, we already know the move — and you hear about it the same day.',
    'card.b.3': '<span class="mono">Gain</span> Fewer days of storage and demurrage, which is exactly where a shipment’s profit evaporates in silence.',
    'card.cta.3': 'Release a stuck shipment',
    'card.n.4': 'S/04',
    'card.h.4': 'Strategic Consulting',
    'card.p.4': 'A tax and logistics review of your current operation: tariff classification, special regimes, drawback, tariff exemptions, trade agreements and route design. This is the front that usually pays for itself before the third shipment.',
    'card.b.4': '<span class="mono">Gain</span> Recurring savings on every future operation, in a report your accountants can actually audit.',
    'card.cta.4': 'Request a review',

    /* processo */
    'proc.h.l1': 'Five stages.',
    'proc.h.l2': 'No <em>surprises.</em>',
    'lead.2': 'Every stage has a defined deliverable, deadline and owner. You always know where your operation stands and what happens next — and that clarity is what removes the fear of importing.',
    'step.t.1': 'Days 1 to 7',
    'step.h.1': 'Planning',
    'step.p.1': 'Product, tariff code, volume and seasonality reviewed; mode, incoterm, tax regime and schedule designed. If an import licence or registration is pending, we settle it now — before any commitment to the supplier.',
    'step.o.1': '<span class="mono">Deliverable</span> Operating plan with a target cost and a target lead time.',
    'step.t.2': 'Weeks 2 to 4',
    'step.h.2': 'Production',
    'step.p.2': 'Supplier approved through document audit and capacity checks, order placed on protected terms, and weekly follow-up on the line. You watch progress without ever entering someone else’s time zone.',
    'step.o.2': '<span class="mono">Deliverable</span> Supplier dossier plus a monitored production schedule.',
    'step.t.3': 'Before shipping',
    'step.h.3': 'Inspection',
    'step.p.3': 'We verify quantity, specification and packing at origin, with a photographic report. Shipping is released only after that — a discrepancy caught at the factory costs a fraction of the same discrepancy found once the container has landed.',
    'step.o.3': '<span class="mono">Deliverable</span> Inspection report with photographs and a conformity certificate.',
    'step.t.4': 'In transit',
    'step.h.4': 'Transport',
    'step.p.4': 'Booking, documentation, insurance and live tracking. You follow it on the dashboard and get a proactive alert on any route deviation, vessel delay or change of port window — before it becomes a calendar problem.',
    'step.o.4': '<span class="mono">Deliverable</span> Access to the control tower plus automated alerts.',
    'step.t.5': 'Arrival',
    'step.h.5': 'Delivery',
    'step.p.5': 'Advance filing, clearance, release and final haul to your dock. We close with the shipment’s real cost set against the budget — so the next operation is more accurate than this one.',
    'step.o.5': '<span class="mono">Deliverable</span> Cargo on your dock plus a financial closing report.',
    'proc.band.1': 'Want to see this process applied to <em>your</em> product and your tariff code?',
    'proc.bandcta.1': 'Book a free review',

    /* resultados */
    'res.h.l1': 'A result is not a',
    'res.h.l2': 'promise. It is an <em>audited</em>',
    'res.h.l3': '<em>number.</em>',
    'num.1': 'Shipments managed since 2016',
    'num.2': 'Average cut in logistics cost in the first year',
    'num.3': 'Cargo cleared on the green channel',
    'num.4': 'Days saved, on average, from order to dock',
    'num.5': 'Countries of origin and destination operated',
    'num.6': 'Of clients still with us after 24 months',
    'res.nota.1': 'Consolidated indicators from the active portfolio. At the review meeting we show the calculation behind them — a number without a source is worth nothing.',

    /* cases */
    'cases.h.l1': 'Proof',
    'cases.h.l2': 'from the <em>field.</em>',
    'lead.3': 'Real companies, names withheld under confidentiality. The figures were audited together with each client’s finance team.',
    'case.tag.1': 'Auto parts manufacturer · São Paulo',
    'case.h.1': 'From 61 to 38 days in the replenishment cycle',
    'case.p.1': 'They were losing sales to stockouts and paying for emergency air freight almost every month. We restructured the mode mix, built a consolidated shipping calendar and moved customs filing forward.',
    'case.k.1': 'days off the cycle', 'case.k.2': 'logistics cost', 'case.k.3': 'emergency air shipments',
    'case.tag.2': 'Electronics e-commerce · Santa Catarina',
    'case.h.2': 'R$ 1.4 million recovered in a tax review',
    'case.p.2': 'Three tariff codes had been classified conservatively for four years. We reworked the classification with a technical opinion, applied a tariff exemption to one line and reopened the operation at the correct cost.',
    'case.k.4': 'accumulated savings', 'case.k.5': 'effective tax burden', 'case.k.6': 'to full payback',
    'case.tag.3': 'Food &amp; agribusiness · Paraná',
    'case.h.3': 'First export in 74 days, to 3 countries',
    'case.p.3': 'The client had never exported. We handled registration, sanitary certificates, label compliance, the international contract and the first shipment — with the buyer paying by letter of credit.',
    'case.k.7': 'in the first half', 'case.k.8': 'margin vs. domestic', 'case.k.9': 'shipments on time',
    'quotes.h.1': 'What the people already running with us say',
    'quote.p.1': 'The difference was not cheaper freight. It was no longer finding out about a problem after it had already become a cost. Today I know on Monday what the whole month will look like.',
    'quote.c.1': 'Industrial director · auto parts',
    'quote.p.2': 'We had worked with three brokers before. What changed here was having someone who understands my product and answers for it. I have never again been stuck in the middle of an argument between the agent and the terminal.',
    'quote.c.2': 'Partner · electronics e-commerce',
    'quote.p.3': 'We thought exporting was something only big companies did. In a little over two months we were shipping. The paperwork that used to block me simply stopped being my problem.',
    'quote.c.3': 'CEO · food manufacturer',
    'quote.p.4': 'The review found a tariff misclassification we had been carrying for years. That alone paid for a full year of the contract. The rest became profit.',
    'quote.c.4': 'CFO · medical equipment',

    /* propósito */
    'purp.h.l1': 'Every Brazilian company',
    'purp.h.l2': 'should be able to compete',
    'purp.h.l3': 'with the <em>whole world.</em>',
    'purp.txt.1': '<p> Foreign trade in Brazil was built to be hard. A language of its own, a bureaucracy that shifts without notice, and a chain of intermediaries in which almost nobody has an incentive to tell you the truth about cost and lead time. </p> <p> The result is that excellent companies give up on importing better, or never try selling abroad at all. They lose margin to competitors who are not better — only better organised internationally. </p> <p> <strong>We exist to erase that disadvantage.</strong> Every operation we simplify is a company that grows without trading predictability for opportunity. In the long run, we want importing and exporting to be as unremarkable as issuing an invoice. </p>',

    /* garantias */
    'offer.h.l1': 'The risk of trying',
    'offer.h.l2': 'is <em>ours.</em> The gain is yours.',
    'offer.kick.1': 'Acelero Review — no cost',
    'offer.h3.1': 'In 45 minutes we show you exactly where your operation is losing money — and how much of it you can recover on the very next shipment.',
    'offer.d.1': 'This is not a sales meeting in disguise. It is a technical analysis of your current operation, run by a senior specialist, with the numbers on screen. If you then want to run it all yourself, the material is yours, with nothing expected in return.',
    'offer.lista.1': '<li>Review of your tariff classification and the regimes that apply to it</li> <li>A <em>landed cost</em> simulation for your main product</li> <li>Mode and route comparison with realistic lead times</li> <li>A map of the three largest customs risks in your current operation</li> <li>An action plan ranked by financial return</li>',
    'offer.cta.1': 'Book my review',
    'offer.sc.1': 'We take on a limited number of new operations each month to protect the standard of service. Slots left in this cycle: <b>4</b>.',
    'gtee.h.1': 'Agreed lead time, guaranteed',
    'gtee.p.1': 'We set a cycle SLA per shipment together with you. If a delay is caused by a failure on our side, the management fee for that shipment is not charged. In writing.',
    'gtee.h.2': 'Cost transparency',
    'gtee.p.2': 'You receive the original invoice from every supplier in the chain. Our fee is declared and fixed — we take no commission buried in freight, currency exchange or storage.',
    'gtee.h.3': 'A reply within 4 business hours',
    'gtee.p.3': 'A direct line to your account manager and to the customs team. A held shipment is resolved in hours, not in days of unanswered email.',
    'bonus.lbl.1': 'Bonuses for closing within the cycle',
    'bonus.lista.1': '<li><b>Digital control tower</b> — the tracking dashboard at no extra cost.</li> <li><b>Audit of 2 suppliers</b> — document verification and an initial inspection.</li> <li><b>Foreign trade playbook</b> — the process written up for your company, for your own team.</li>',

    /* FAQ */
    'faq.h.l1': 'Questions everyone',
    'faq.h.l2': 'asks before',
    'faq.h.l3': '<em>getting started.</em>',
    'lead.4': 'If your question is not here, send it on WhatsApp. We answer with the technical answer, even when it does not help the sale.',
    'faq.q.1': 'My company has never imported. Can we start from zero?',
    'faq.a.1': 'You can, and it is the most common situation among our new clients. We handle the customs registration, the tax framework, the choice of supplier and the entire first shipment. You take the commercial decisions; the technical side stays with us.',
    'faq.q.2': 'What is the minimum volume to make it worthwhile?',
    'faq.a.2': 'We do not work to a rigid minimum, we work to viability. Operations from roughly one container per quarter, or recurring air cargo, usually carry enough gain. At the review we say plainly if it is not yet your moment — wasting time on an operation that does not add up is bad for both sides.',
    'faq.q.3': 'How do you charge?',
    'faq.a.3': 'We agree in advance on either a management fee per shipment or a monthly retainer, depending on volume. Third-party costs — freight, insurance, storage, duties, port charges — are passed through with the original invoice attached. No buried commission: if a partner pays us anything, it is declared and deducted.',
    'faq.q.4': 'Do you guarantee the delivery date?',
    'faq.a.4': 'We guarantee the SLA on the stages under our management, set out in the contract. A port strike, a weather event or an extraordinary inspection are beyond any operator’s control — but in those cases you are told immediately, with a plan B on the table. When the delay comes from a failure on our side, the management fee for that shipment is not charged.',
    'faq.q.5': 'What if my cargo is flagged for inspection?',
    'faq.a.5': 'It is part of the operation and no cause for panic. Our paperwork is checked before arrival precisely to reduce that chance — and when it happens, the customs team takes over the dialogue with the authorities and the terminal the same day. Today, 98.4% of our cargo clears on the green channel.',
    'faq.q.6': 'Do you work with suppliers in China?',
    'faq.a.6': 'Yes, and also in India, Vietnam, Turkey, the United States, Mexico and the European Union. We have inspection partners at origin, which means your product’s conformity is verified before shipping — not once the container is already in Brazil.',
    'faq.q.7': 'I already have a customs broker. Do I have to replace everything?',
    'faq.a.7': 'No. Many clients start with strategic consulting or logistics alone, keeping their current broker. If consolidating later makes sense, we run the transition without interrupting shipments in progress.',
    'faq.q.8': 'How do I follow my operations day to day?',
    'faq.a.8': 'Through the digital control tower: the status of each shipment, documents, accumulated cost and an updated ETA, on desktop or phone. On top of that you have a direct line to your account manager, answered within 4 business hours.',
    'faq.q.9': 'Is the review really free?',
    'faq.a.9': 'It is. We invest those 45 minutes because, in practice, it is our best demonstration of competence. You leave with the material in hand, whether you hire us or not. What we ask in return is that whoever joins the meeting has access to the operation’s numbers — without them, the analysis becomes guesswork.',

    /* contato */
    'cont.h.l1': 'Talk to a',
    'cont.h.l2': '<em>specialist</em> now.',
    'cont.lead.1': 'Fill in the form and a senior specialist — not a screening agent — will get in touch within 1 business day to schedule the review. If you prefer, message us directly on WhatsApp.',
    'chan.em.1': 'WhatsApp — answered within minutes, in business hours',
    'chan.em.2': 'Landline, 8:30 to 18:30',
    'chan.em.3': 'For proposals, RFPs and documentation',
    'cont.re.1': '<b>No obligation and no cost.</b> You leave the meeting with the map of your operation, whether you hire us or not. Your data is not shared with third parties.',
    'form.t.1': 'Request an operation review',
    'form.lbl.1': 'Full name *', 'form.lbl.2': 'Company *', 'form.lbl.3': 'Work email *',
    'form.lbl.4': 'WhatsApp *', 'form.lbl.5': 'What do you need? *',
    'form.lbl.6': 'Estimated volume', 'form.lbl.7': 'Tell us briefly about the operation',
    'form.conf.t': 'Confirm the number — this is how we will reach you',
    'form.conf.c': 'I have already sent the confirmation message from my WhatsApp.',
    'form.conf.l': 'Send the confirmation from my WhatsApp',
    'form.conf.k': 'Reference code',
    'form.cta.1': 'Request my free review',
    'form.n.1': 'Answered within 1 business day. No spam.',

    /* rodapé */
    'foot.h.l1': 'Your next import',
    'foot.h.l2': 'could be the <em>calmest</em>',
    'foot.h.l3': '<em>one</em> yet.',
    'foot.cta.1': 'Talk to a specialist',
    'foot.desc.1': 'Complete foreign trade management for manufacturers, e-commerce operations and importers who cannot afford to rely on luck.',
    'foot.serv.1': 'Import and Export', 'foot.serv.2': 'International Logistics',
    'foot.serv.3': 'Customs Clearance', 'foot.serv.4': 'Strategic Consulting',
    'foot.emp.1': 'About Acelero', 'foot.emp.2': 'Process', 'foot.emp.3': 'Cases',
    'foot.emp.4': 'Why we do it', 'foot.emp.5': 'Frequently asked questions',
    'foot.hora': 'Mon to Fri, 8:30 to 18:30',
    'foot.lbl.1': 'Services', 'foot.lbl.2': 'Company', 'foot.lbl.3': 'Contact'
  },

  es: {
    /* navegación */
    'nav.sobre': '<span class="mono">01</span>Nosotros',
    'nav.servicos': '<span class="mono">02</span>Servicios',
    'nav.processo': '<span class="mono">03</span>Proceso',
    'nav.cases': '<span class="mono">05</span>Casos',
    'nav.contato': '<span class="mono">09</span>Contacto',
    'nav.cta': 'Agendar consultoría',
    'menu.1': 'Sobre Acelero', 'menu.2': 'Servicios', 'menu.3': 'Proceso',
    'menu.4': 'Resultados', 'menu.5': 'Casos', 'menu.6': 'Por qué lo hacemos',
    'menu.7': 'Garantías', 'menu.8': 'Preguntas frecuentes',
    'menu.9': 'Hablar con un especialista',

    /* hero */
    'hero.tag.1': 'Gestión integral de comercio exterior',
    'hero.h.l1': 'Conectando',
    'hero.h.l2': 'el mundo a través',
    'hero.h.l3': 'del <em>comercio exterior.</em>',
    'hero.sub.1': 'Gestión integral de importación y exportación con eficiencia y confianza — <strong>del pedido al proveedor hasta la carga en su muelle</strong>, con el costo cerrado antes de que usted apruebe la compra.',
    'hero.cta1.1': 'Agendar consultoría',
    'hero.cta2.1': 'Qué hacemos',
    'hero.kpi.1': 'embarques gestionados',
    'hero.kpi.2': 'países operados',
    'hero.kpi.3': 'liberadas en canal verde',
    'hero.kpi.4': 'siguen tras 24 meses',
    'hero.role.1': 'Baje',

    /* secciones — numeración */
    'hdnum.1': '01 — Nosotros', 'hdnum.2': '02 — Servicios', 'hdnum.3': '03 — Proceso',
    'hdnum.4': '04 — Resultados', 'hdnum.5': '05 — Casos', 'hdnum.6': '06 — Por qué lo hacemos',
    'hdnum.7': '07 — Garantías', 'hdnum.8': '08 — Dudas', 'hdnum.9': '09 — Contacto',

    /* nosotros */
    'sobre.h.l1': 'No somos otro',
    'sobre.h.l2': 'intermediario. Somos su',
    'sobre.h.l3': '<em>departamento</em>',
    'sobre.h.l4': '<em>de comercio exterior.</em>',
    'sobre.txt.1': '<p> ACELERO COMEX nació de una inconformidad simple: las empresas brasileñas pierden margen, tiempo y noches de sueño porque la operación internacional se trata como un rompecabezas de proveedores desconectados — uno cotiza, otro embarca, otro despacha en aduana, y nadie responde por el resultado. </p> <p> Nosotros reunimos todo bajo un solo equipo, un solo proceso y un solo responsable. Usted habla con una persona; nosotros coordinamos el resto del planeta. </p>',
    'tri.lbl.1': 'Misión',
    'tri.h.1': 'Hacer el mundo accesible para quien produce y vende en Brasil.',
    'tri.p.1': 'Acortar la distancia entre su empresa y cualquier proveedor o cliente del planeta, con claridad total de costo, plazo y riesgo.',
    'tri.lbl.2': 'Visión',
    'tri.h.2': 'Ser la operación de comercio exterior más previsible de América Latina.',
    'tri.p.2': 'No la más grande. La más confiable — aquella en la que la dirección planifica el trimestre entero sin temer lo que viene del otro lado del océano.',
    'tri.lbl.3': 'Valores',
    'tri.h.3': 'Transparencia radical, dato antes que opinión, responsabilidad de punta a punta.',
    'tri.p.3': 'Si algo sale mal, usted se entera por nosotros — antes de que se convierta en pérdida. Sin tarifas ocultas, sin “eso no nos corresponde”.',

    /* servicios */
    'serv.h.l1': 'Cuatro frentes.',
    'serv.h.l2': 'Una <em>sola</em> operación.',
    'lead.1': 'Puede contratar un frente aislado o entregar toda la operación a nuestro equipo. En la práctica, quien empieza por uno termina migrando todo — porque la ganancia está justamente en que nadie pueda pasarle la responsabilidad al de al lado.',
    'card.n.1': 'S/01',
    'card.h.1': 'Importación y Exportación',
    'card.p.1': 'Desde la homologación del proveedor hasta la nacionalización — y, en el otro sentido, desde la adecuación de etiqueta hasta el certificado de origen. Simulación de <em>landed cost</em> antes de que apruebe la compra, no después de que llegue la factura.',
    'card.b.1': '<span class="mono">Ganancia</span> Usted decide comprar sabiendo el costo final en su propio estante, con el margen calculado y no estimado.',
    'card.cta.1': 'Simular mi operación',
    'card.n.2': 'S/02',
    'card.h.2': 'Logística Internacional',
    'card.p.2': 'Marítimo, aéreo, terrestre y multimodal con contratos negociados por volumen. Elegimos el modal por su calendario de ventas, no por la conveniencia del agente — y monitoreamos cada tramo hasta el muelle de destino.',
    'card.b.2': '<span class="mono">Ganancia</span> Flete competitivo con espacio garantizado en temporada alta y un ETA que usted puede prometerle a su cliente.',
    'card.cta.2': 'Cotizar mi flete',
    'card.n.3': 'S/03',
    'card.h.3': 'Despacho Aduanero',
    'card.p.3': 'Equipo propio de despacho, documentación revisada antes del arribo y relación diaria con las terminales. Cuando una carga cae en canal amarillo o rojo, ya sabemos qué hacer — y usted se entera el mismo día.',
    'card.b.3': '<span class="mono">Ganancia</span> Menos días de almacenaje y demoras, que es donde la utilidad del embarque se evapora en silencio.',
    'card.cta.3': 'Destrabar una carga',
    'card.n.4': 'S/04',
    'card.h.4': 'Consultoría Estratégica',
    'card.p.4': 'Diagnóstico tributario y logístico de la operación actual: revisión de clasificación arancelaria, regímenes especiales, drawback, exenciones arancelarias, acuerdos comerciales y diseño de ruta. Es el frente que suele pagarse solo antes del tercer embarque.',
    'card.b.4': '<span class="mono">Ganancia</span> Ahorro recurrente en cada operación futura, con un informe que su contabilidad puede auditar.',
    'card.cta.4': 'Pedir un diagnóstico',

    /* proceso */
    'proc.h.l1': 'Cinco etapas.',
    'proc.h.l2': 'Ninguna <em>sorpresa.</em>',
    'lead.2': 'Cada etapa tiene entregable, plazo y responsable definidos. Usted siempre sabe en qué punto está su operación y qué viene después — es esa claridad la que elimina el miedo a importar.',
    'step.t.1': 'Días 1 a 7',
    'step.h.1': 'Planificación',
    'step.p.1': 'Diagnóstico de producto, clasificación arancelaria, volumen y estacionalidad; diseño de modal, incoterm, régimen tributario y cronograma. Si hay una habilitación o licencia pendiente, la resolvemos ahora — antes de cualquier compromiso con el proveedor.',
    'step.o.1': '<span class="mono">Entregable</span> Plan operativo con costo objetivo y plazo objetivo.',
    'step.t.2': 'Semanas 2 a 4',
    'step.h.2': 'Producción',
    'step.p.2': 'Proveedor homologado mediante auditoría documental y verificación de capacidad productiva, pedido firmado con términos protegidos y seguimiento semanal de la línea. Usted sigue el avance sin entrar en ningún huso horario ajeno.',
    'step.o.2': '<span class="mono">Entregable</span> Expediente del proveedor + cronograma de producción monitoreado.',
    'step.t.3': 'Antes del embarque',
    'step.h.3': 'Inspección',
    'step.p.3': 'Verificamos cantidad, especificación y embalaje en origen, con informe fotográfico. El embarque se libera solo después de eso — una discrepancia detectada en la fábrica cuesta una fracción de lo que cuesta con el contenedor ya en destino.',
    'step.o.3': '<span class="mono">Entregable</span> Informe de inspección con fotos y certificado de conformidad.',
    'step.t.4': 'Tránsito internacional',
    'step.h.4': 'Transporte',
    'step.p.4': 'Booking, documentación, seguro y rastreo en tiempo real. Usted lo sigue en el panel y recibe alerta proactiva ante cualquier desvío de ruta, retraso de buque o cambio de ventana portuaria — antes de que se vuelva un problema de agenda.',
    'step.o.4': '<span class="mono">Entregable</span> Acceso a la torre de control + alertas automáticas.',
    'step.t.5': 'Arribo',
    'step.h.5': 'Entrega',
    'step.p.5': 'Registro anticipado, despacho, liberación y transporte final hasta su muelle. Cerramos con el costo real del embarque comparado con lo presupuestado — para que la próxima operación sea aún más precisa que esta.',
    'step.o.5': '<span class="mono">Entregable</span> Carga en su muelle + informe de cierre financiero.',
    'proc.band.1': '¿Quiere ver este proceso aplicado a <em>su</em> producto y su clasificación arancelaria?',
    'proc.bandcta.1': 'Agendar diagnóstico gratuito',

    /* resultados */
    'res.h.l1': 'Un resultado no es',
    'res.h.l2': 'promesa. Es <em>número</em>',
    'res.h.l3': '<em>auditado.</em>',
    'num.1': 'Embarques gestionados desde 2016',
    'num.2': 'Reducción media de costo logístico en el primer año',
    'num.3': 'Cargas liberadas en canal verde',
    'num.4': 'Menos, en promedio, en el ciclo pedido → muelle',
    'num.5': 'Países de origen y destino operados',
    'num.6': 'De los clientes siguen con nosotros tras 24 meses',
    'res.nota.1': 'Indicadores consolidados de la cartera activa. En la reunión de diagnóstico mostramos la memoria de cálculo — un número sin origen no vale nada.',

    /* casos */
    'cases.h.l1': 'Pruebas',
    'cases.h.l2': 'de <em>campo.</em>',
    'lead.3': 'Empresas reales, con nombres reservados por acuerdo de confidencialidad. Las cifras fueron auditadas junto con el equipo financiero de cada cliente.',
    'case.tag.1': 'Industria de autopartes · São Paulo',
    'case.h.1': 'De 61 a 38 días en el ciclo de reposición',
    'case.p.1': 'Perdía ventas por quiebre de stock y pagaba aéreo de emergencia casi todos los meses. Reestructuramos la mezcla de modales, creamos un calendario de embarques consolidados y adelantamos el registro aduanero.',
    'case.k.1': 'días menos de ciclo', 'case.k.2': 'costo logístico', 'case.k.3': 'aéreos de emergencia',
    'case.tag.2': 'E-commerce de electrónicos · Santa Catarina',
    'case.h.2': 'R$ 1,4 millones recuperados en revisión tributaria',
    'case.p.2': 'Tres clasificaciones arancelarias estaban definidas de forma conservadora desde hacía cuatro años. Rehicimos el encuadre con dictamen técnico, aplicamos una exención arancelaria en una línea y reabrimos la operación con el costo correcto.',
    'case.k.4': 'ahorro acumulado', 'case.k.5': 'carga tributaria', 'case.k.6': 'para el retorno',
    'case.tag.3': 'Alimentos &amp; agro · Paraná',
    'case.h.3': 'Primera exportación en 74 días, a 3 países',
    'case.p.3': 'El cliente nunca había exportado. Nos encargamos de la habilitación, los certificados sanitarios, la adecuación de etiqueta, el contrato internacional y el primer embarque — con el comprador pagando por carta de crédito.',
    'case.k.7': 'en el 1er semestre', 'case.k.8': 'margen vs. interno', 'case.k.9': 'embarques en plazo',
    'quotes.h.1': 'Lo que dicen quienes ya operan con nosotros',
    'quote.p.1': 'La diferencia no fue el flete más barato. Fue dejar de descubrir el problema cuando ya se había convertido en costo. Hoy sé el lunes lo que va a pasar el mes entero.',
    'quote.c.1': 'Director industrial · autopartes',
    'quote.p.2': 'Ya habíamos trabajado con tres despachantes. Lo que cambió aquí fue tener a alguien que entiende mi producto y responde por él. Nunca más quedé en medio de una discusión entre el agente y la terminal.',
    'quote.c.2': 'Socia · e-commerce de electrónicos',
    'quote.p.3': 'Pensábamos que exportar era cosa de empresas grandes. En poco más de dos meses estábamos embarcando. La burocracia, que me trababa, simplemente dejó de ser un problema mío.',
    'quote.c.3': 'CEO · industria de alimentos',
    'quote.p.4': 'El diagnóstico detectó una clasificación fiscal equivocada que arrastrábamos hacía años. Solo eso ya pagó el contrato de un año entero. El resto se volvió utilidad.',
    'quote.c.4': 'CFO · equipos médicos',

    /* propósito */
    'purp.h.l1': 'Toda empresa brasileña',
    'purp.h.l2': 'debería poder competir',
    'purp.h.l3': 'con el <em>mundo entero.</em>',
    'purp.txt.1': '<p> El comercio exterior en Brasil fue construido para ser difícil. Un lenguaje propio, una burocracia que cambia sin aviso y una cadena de intermediarios en la que casi nadie tiene incentivo para decir la verdad sobre costo y plazo. </p> <p> El resultado es que empresas excelentes desisten de importar mejor, o nunca prueban vender afuera. Pierden margen frente a competidores que no son mejores — solo tienen una operación internacional más organizada. </p> <p> <strong>Existimos para borrar esa desventaja.</strong> Cada operación que simplificamos es una empresa que crece sin cambiar previsibilidad por oportunidad. A largo plazo, queremos que importar y exportar sea tan corriente como emitir una factura. </p>',

    /* garantías */
    'offer.h.l1': 'El riesgo de intentar',
    'offer.h.l2': 'es <em>nuestro.</em> La ganancia es suya.',
    'offer.kick.1': 'Diagnóstico Acelero — sin costo',
    'offer.h3.1': 'En 45 minutos le mostramos exactamente dónde su operación pierde dinero — y cuánto puede recuperar ya en el próximo embarque.',
    'offer.d.1': 'No es una reunión comercial disfrazada. Es un análisis técnico de su operación actual, hecho por un especialista sénior, con los números en pantalla. Si después de eso quiere llevarlo todo solo, el material es suyo, sin contrapartida.',
    'offer.lista.1': '<li>Revisión de su clasificación arancelaria y de los regímenes aplicables</li> <li>Simulación de <em>landed cost</em> de su principal producto</li> <li>Comparativo de modales y rutas con plazos realistas</li> <li>Mapa de los tres mayores riesgos aduaneros de la operación actual</li> <li>Plan de acción priorizado por retorno financiero</li>',
    'offer.cta.1': 'Agendar mi diagnóstico',
    'offer.sc.1': 'Atendemos un número limitado de nuevas operaciones por mes para mantener el estándar de acompañamiento. Cupos del ciclo actual: <b>4</b>.',
    'gtee.h.1': 'Garantía del plazo acordado',
    'gtee.p.1': 'Definimos con usted un SLA de ciclo por embarque. Si el retraso se debe a una falla nuestra, la tarifa de gestión de ese embarque no se cobra. Por contrato.',
    'gtee.h.2': 'Transparencia de costo',
    'gtee.p.2': 'Usted recibe la factura original de cada proveedor de la cadena. Nuestra remuneración es declarada y fija — no ganamos comisión incorporada en flete, cambio de divisas ni almacenaje.',
    'gtee.h.3': 'Respuesta en hasta 4 horas hábiles',
    'gtee.p.3': 'Canal directo con su gerente de cuenta y con el equipo de aduana. Una carga detenida se resuelve en horas, no en días de correos sin respuesta.',
    'bonus.lbl.1': 'Bonos para quien cierra en el ciclo',
    'bonus.lista.1': '<li><b>Torre de control digital</b> — panel de seguimiento sin costo adicional.</li> <li><b>Auditoría de 2 proveedores</b> — verificación documental e inspección inicial.</li> <li><b>Playbook de comercio exterior</b> — el proceso aplicado a su empresa, para su equipo interno.</li>',

    /* preguntas */
    'faq.h.l1': 'Preguntas que todos',
    'faq.h.l2': 'hacen antes',
    'faq.h.l3': '<em>de empezar.</em>',
    'lead.4': 'Si su duda no está aquí, escríbanos por WhatsApp. Respondemos con la respuesta técnica, incluso cuando no favorece la venta.',
    'faq.q.1': 'Mi empresa nunca importó. ¿Se puede empezar desde cero?',
    'faq.a.1': 'Se puede, y es el escenario más común entre nuestros clientes nuevos. Nos ocupamos de la habilitación aduanera, del encuadre tributario, de la elección del proveedor y del primer embarque completo. Usted participa de las decisiones comerciales; la parte técnica queda con nosotros.',
    'faq.q.2': '¿Cuál es el volumen mínimo para que valga la pena?',
    'faq.a.2': 'No trabajamos con un mínimo rígido, sino con viabilidad. Operaciones a partir de cerca de un contenedor por trimestre, o cargas aéreas recurrentes, ya suelen tener ganancia suficiente. En el diagnóstico decimos con claridad si aún no es su momento — perder tiempo con una operación que no cierra es malo para ambos lados.',
    'faq.q.3': '¿Cómo cobran ustedes?',
    'faq.a.3': 'Acordamos previamente una tarifa de gestión por embarque o un fee mensual, según el volumen. Los costos de terceros — flete, seguro, almacenaje, tributos, tasas portuarias — se trasladan con la factura original adjunta. Sin comisión incorporada: si un socio nos paga algo, se declara y se descuenta.',
    'faq.q.4': '¿Garantizan el plazo de entrega?',
    'faq.a.4': 'Garantizamos el SLA de las etapas bajo nuestra gestión, definido por contrato. Una huelga portuaria, un evento climático o una fiscalización extraordinaria están fuera del control de cualquier operador — pero en esos casos usted es avisado de inmediato, con un plan B sobre la mesa. Cuando el retraso proviene de una falla nuestra, la tarifa de gestión de ese embarque no se cobra.',
    'faq.q.5': '¿Y si mi carga cae en canal amarillo o rojo?',
    'faq.a.5': 'Es parte de la operación y no es motivo de pánico. Nuestra documentación se revisa antes del arribo justamente para reducir esa probabilidad — y, cuando ocurre, el equipo de aduana asume la interlocución con la autoridad y con la terminal el mismo día. Hoy, el 98,4% de nuestras cargas se liberan en canal verde.',
    'faq.q.6': '¿Trabajan con proveedores de China?',
    'faq.a.6': 'Sí, y también con India, Vietnam, Turquía, Estados Unidos, México y la Unión Europea. Tenemos socios de inspección en origen, lo que significa que la conformidad de su producto se verifica antes del embarque — no cuando el contenedor ya está en destino.',
    'faq.q.7': 'Ya tengo despachante. ¿Tengo que cambiar todo?',
    'faq.a.7': 'No. Muchos clientes empiezan solo por la consultoría estratégica o por la logística, manteniendo su despachante actual. Si en algún momento tiene sentido consolidar, la transición la hacemos nosotros, sin interrumpir embarques en curso.',
    'faq.q.8': '¿Cómo sigo mis operaciones en el día a día?',
    'faq.a.8': 'Por la torre de control digital: estado de cada embarque, documentos, costo acumulado y ETA actualizado, en la computadora o en el celular. Además, tiene canal directo con el gerente de cuenta, con respuesta en hasta 4 horas hábiles.',
    'faq.q.9': '¿El diagnóstico es realmente gratuito?',
    'faq.a.9': 'Lo es. Invertimos esos 45 minutos porque, en la práctica, es nuestra mejor demostración de competencia. Usted se va con el material en la mano, nos contrate o no. Lo que pedimos a cambio es que quien participe de la reunión tenga acceso a los números de la operación — sin eso, el análisis se vuelve suposición.',

    /* contacto */
    'cont.h.l1': 'Hable con un',
    'cont.h.l2': '<em>especialista</em> ahora.',
    'cont.lead.1': 'Complete el formulario y un especialista sénior — no un agente de filtro — lo contactará en hasta 1 día hábil para agendar el diagnóstico. Si prefiere, escríbanos directo por WhatsApp.',
    'chan.em.1': 'WhatsApp — respuesta en minutos, en horario comercial',
    'chan.em.2': 'Teléfono fijo, de 8:30 a 18:30',
    'chan.em.3': 'Para propuestas, licitaciones y documentación',
    'cont.re.1': '<b>Sin compromiso y sin costo.</b> Usted sale de la reunión con el mapa de su operación, nos contrate o no. Sus datos no se comparten con terceros.',
    'form.t.1': 'Solicitar análisis de la operación',
    'form.lbl.1': 'Nombre completo *', 'form.lbl.2': 'Empresa *', 'form.lbl.3': 'Correo corporativo *',
    'form.lbl.4': 'WhatsApp *', 'form.lbl.5': '¿Qué necesita? *',
    'form.lbl.6': 'Volumen estimado', 'form.lbl.7': 'Cuéntenos brevemente sobre la operación',
    'form.conf.t': 'Confirme el número — por ahí lo vamos a contactar',
    'form.conf.c': 'Ya envié el mensaje de confirmación desde mi WhatsApp.',
    'form.conf.l': 'Enviar la confirmación desde mi WhatsApp',
    'form.conf.k': 'Código de esta solicitud',
    'form.cta.1': 'Solicitar mi análisis gratuito',
    'form.n.1': 'Respuesta en hasta 1 día hábil. Sin spam.',

    /* pie */
    'foot.h.l1': 'Su próxima importación',
    'foot.h.l2': 'puede ser la <em>más</em>',
    'foot.h.l3': '<em>tranquila</em> de todas.',
    'foot.cta.1': 'Hablar con un especialista',
    'foot.desc.1': 'Gestión integral de comercio exterior para industrias, e-commerces e importadores que no pueden depender de la suerte.',
    'foot.serv.1': 'Importación y Exportación', 'foot.serv.2': 'Logística Internacional',
    'foot.serv.3': 'Despacho Aduanero', 'foot.serv.4': 'Consultoría Estratégica',
    'foot.emp.1': 'Sobre Acelero', 'foot.emp.2': 'Proceso', 'foot.emp.3': 'Casos',
    'foot.emp.4': 'Por qué lo hacemos', 'foot.emp.5': 'Preguntas frecuentes',
    'foot.hora': 'Lun a vie, 8:30 a 18:30',
    'foot.lbl.1': 'Servicios', 'foot.lbl.2': 'Empresa', 'foot.lbl.3': 'Contacto'
  }
};

/* Textos que não vivem em elementos com data-i18n: placeholders do formulário,
   opções dos selects e as mensagens que o JavaScript emite. */
window.ACELERO_IDIOMAS_EXTRA = {
  en: {
    placeholders: {
      nome: 'What should we call you?', empresa: 'Registered or trading name',
      email: 'you@yourcompany.com', telefone: '+55 (00) 00000-0000',
      mensagem: 'Product, country of origin or destination, target date, biggest difficulty today…'
    },
    opcoes: {
      interesse: ['Select…', 'Import (already importing)', 'Import (never imported)', 'Export',
                  'International logistics / freight', 'Customs clearance',
                  'Consulting and tax review', 'Release an urgent shipment'],
      volume: ['Select…', 'Not sure yet', 'Up to 2 containers/year', '3 to 12 containers/year',
               'More than 12 containers/year', 'Air freight / courier only']
    },
    cursor: {
      'Agendar': 'Book', 'Ver': 'View', 'Detalhes': 'Details', 'Vamos?': 'Let’s go',
      'Planejamento': 'Planning', 'Produção': 'Production', 'Inspeção': 'Inspection',
      'Transporte': 'Transport', 'Entrega': 'Delivery', 'Ligar': 'Call',
      'E-mail': 'Email', 'Enviar': 'Send', 'WhatsApp': 'WhatsApp',
      'Ir': 'Go', 'Abrir': 'Open', 'Ler': 'Read', 'Fechar': 'Close',
      'Digite': 'Type', 'Escolha': 'Choose', 'Marcar': 'Tick', 'Clique': 'Click',
      'Idioma': 'Language'
    },
    consentimento: 'I authorise ACELERO COMEX to contact me and I agree to the <a href="politica-privacidade.html">Privacy Policy</a>. *',
    msg: {
      enviando: 'Sending…',
      ok: 'Received. A specialist will be in touch within 1 business day.',
      erro: 'We could not send it right now. Message us on WhatsApp and we will sort it out.',
      campos: 'Check the highlighted fields above.',
      nome: 'Please enter your name.', empresa: 'Please enter the company name.',
      interesse: 'Please select what you need.', email: 'Please enter a valid email.',
      telefone: 'Please enter a WhatsApp number with area code.',
      consent: 'You need to authorise contact before sending.',
      telDig: 'Number is incomplete for the country you selected.',
      telLongo: 'Number has too many digits for the country you selected.',
      telFalso: 'This does not look like a real number. Please check it.',
      telDDD: 'That Brazilian area code does not exist. Check the first two digits.',
      telCel: 'WhatsApp in Brazil is a mobile line: 11 digits, with a 9 after the area code.',
      emailCorp: 'Please use your company email. We do not take enquiries from personal email.',
      waEnvio: 'Send the confirmation message on WhatsApp — that is how we know the number is yours.',
      waConf: 'Tick the WhatsApp confirmation so we can reach you.'
    }
  },
  es: {
    placeholders: {
      nome: '¿Cómo podemos llamarlo?', empresa: 'Razón social o nombre comercial',
      email: 'usted@suempresa.com', telefone: '+55 (00) 00000-0000',
      mensagem: 'Producto, país de origen o destino, plazo deseado, principal dificultad hoy…'
    },
    opcoes: {
      interesse: ['Seleccione…', 'Importar (ya importo)', 'Importar (nunca importé)', 'Exportar',
                  'Logística internacional / flete', 'Despacho aduanero',
                  'Consultoría y revisión tributaria', 'Destrabar una carga urgente'],
      volume: ['Seleccione…', 'Aún no sé estimar', 'Hasta 2 contenedores/año',
               '3 a 12 contenedores/año', 'Más de 12 contenedores/año', 'Solo carga aérea / courier']
    },
    cursor: {
      'Agendar': 'Agendar', 'Ver': 'Ver', 'Detalhes': 'Detalles', 'Vamos?': '¿Vamos?',
      'Planejamento': 'Planificación', 'Produção': 'Producción', 'Inspeção': 'Inspección',
      'Transporte': 'Transporte', 'Entrega': 'Entrega', 'Ligar': 'Llamar',
      'E-mail': 'Correo', 'Enviar': 'Enviar', 'WhatsApp': 'WhatsApp',
      'Ir': 'Ir', 'Abrir': 'Abrir', 'Ler': 'Leer', 'Fechar': 'Cerrar',
      'Digite': 'Escriba', 'Escolha': 'Elija', 'Marcar': 'Marcar', 'Clique': 'Clic',
      'Idioma': 'Idioma'
    },
    consentimento: 'Autorizo el contacto de ACELERO COMEX y acepto la <a href="politica-privacidade.html">Política de Privacidad</a>. *',
    msg: {
      enviando: 'Enviando…',
      ok: 'Recibido. Un especialista lo contactará en hasta 1 día hábil.',
      erro: 'No pudimos enviarlo ahora. Escríbanos por WhatsApp y lo resolvemos.',
      campos: 'Revise los campos destacados arriba.',
      nome: 'Informe su nombre.', empresa: 'Informe el nombre de la empresa.',
      interesse: 'Seleccione lo que necesita.', email: 'Informe un correo válido.',
      telefone: 'Informe un WhatsApp con código de área.',
      consent: 'Es necesario autorizar el contacto para enviar.',
      telDig: 'Número incompleto para el país elegido.',
      telLongo: 'Número con demasiados dígitos para el país elegido.',
      telFalso: 'Este número no parece real. Verifíquelo e ingréselo de nuevo.',
      telDDD: 'Ese código de área brasileño no existe. Revise los dos primeros dígitos.',
      telCel: 'En Brasil WhatsApp es celular: 11 dígitos, con el 9 después del código de área.',
      emailCorp: 'Use el correo de la empresa. No atendemos por correo personal.',
      waEnvio: 'Envíe el mensaje de confirmación por WhatsApp — así sabemos que el número es suyo.',
      waConf: 'Marque la confirmación de WhatsApp para que podamos contactarlo.'
    }
  }
};
